source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'mysql2'
gem "omniauth"  
gem "omniauth-instagram"
gem "instagram"
gem "mini_magick"
gem 'carrierwave'
gem 'delayed_job_active_record'
gem "twitter-bootstrap-rails"
gem 'will_paginate-bootstrap'
gem 'will_paginate', '~> 3.0'
gem 'acts_as_commentable_with_threading'

gem 'haml'
# forms
gem 'simple_form'
gem 'nested_form'

gem 'tinymce-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'fancybox-rails'

group :development do
  gem 'debugger'
  gem 'thin'
end
